version: 2
jobs:
  build:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/qutheory/connect-dashboard
      - restore_cache:
          key: v1-package-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-package-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  lint:
    docker:
        - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/qutheory/connect-dashboard
      - run: npm run lint

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - lint
